# Site settings
title: Francho(lab)... forjando ideicas
email: pub@francho.org
description: >
  Francho Joven Araus (aka @francholab). Unutopico, maño, geek, artesano de software, aprendiz ágil, programador en activo, sysop retirado, emocionado con Zagales Hacklab, papá a tiempo completo...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://francho.org" # the base hostname & protocol for your site
timezone: Europe/Madrid

permalink: /:year/:month/:day/:title/

twitter_username: francholab
github_username:  francho
google-tracking-id: "UA-299756-5"
disqus-shortname: "francho"

# Build settings
highlighter: rouge
markdown: kramdown

pages_list:
  'Blog': 'blog'
  'Acerca de...': 'acerca-de'
  'Contacto': 'contacto'

background-img: "/img/intro-bg.jpg"

# About variables

me-img: "/img/me.jpg"

# Blog variables
paginate: 15

paginate_path: "blog/page:num"

post-preview-words: 128

# Career variables

events:
  - image: "/assets/career/frogtek.png"
    date: "2018 - actualmente"
    description: "El círculo se cierra, programador Android en <a href='http://fogtek.org'>Frogtek</a>  "
  - image: "/assets/career/spines.png"
    date: "2014-2018"
    description: "Quería trabajar en una empresa ágil de verdad, una con un proyecto interesante y crear un producto desde cero así que me alisté en <a href='/2014/12/31/mi-2014-el-ano-del-cambio/'>Spines</a>. Devop. Product Manager <strong>Ruby, Angular</strong>"
  - image: "/assets/career/zagales.png"
    date: "2012"
    description: "Preocupados por la educación tecnológica de nuestros hijos montamos <a href='http://zagales-hacklab.org/quienes-somos/'>Zagales Hacklab</a>"
  - image: "/assets/career/unutopia.png"
    date: "2012"
    description: "Tras un fin de semana inolvidable en un pueblecito perdido del Pirineo nació <a href='/2012/10/01/unutopia-otra-forma-es-posible/'>Unutopia</a>"
  - image: "/assets/career/ainsa.png"
    date: "2011-2014"
    description: "Perseguí el sueño de vivir y trabajar desde la montaña, pero se escapó. Programador <strong>Android, Objective-c, Php, Angular</strong>"
  - image: "/assets/career/pocket.png"
    date: "2010-2011"
    description: "Muchos proyectos distintos en poco tiempo, fue estresante, pero aprendí un montón. Escritor, profesor, programador <strong>C, Java, Android</strong>"
  - image: "/assets/career/out.png"
    date: "2010"
    description: "Gracias al empujón de los cracks de <a href='http://frogtek.org/'>Frogtek</a>, decidí salir de mi cueva y conocí a mas cracks de <a href='http://agile-aragon.org/'>Agile Aragon</a> y <a href='http://cachirulo-valley.com'>Cachirulo Valley</a> "
  - image: "/assets/career/android.png"
    date: "2009-2010"
    description: "Necesitaba un cambio de rumbo y <a href='/2010/10/03/hace-dos-anos/'>decidí tomarme un año sabatico</a> (sólo aguanté unos meses). <strong>Python, Java, Android</strong>"
  - image: "/assets/career/tux.png"
    date: "1999-2009"
    description: "Programador backend, Administrador de sistemas. <strong>Linux, PHP.</strong>"
  - image: "/assets/career/sanvalero.png"
    date: "1997-1999"
    description: "Profesor, programador web. <strong>PHP, C, VisualBasic</strong> (y otros de cuyo nombre no quiero acordarme)"
  - image: "/assets/career/cardiff.png"
    date: "1993-1997"
    description: "BSc Business Information Systems (San Valero / Cardiff University)"

# First image of the Career timeline
career-img: "/img/me.jpg"

# Social networks variables (many more available: facebook, flickr, dribbble, pinterest, instagram, tumblr etc.)
social:
  - title: "rss"
    url: "/feed.xml"
  - title: "twitter"
    url: "https://twitter.com/francholab"
  - title: "github"
    url: "https://github.com/francho"
  - title: "linkedin"
    url: "http://no.linkedin.com/in/francho"

favicon: "/img/favicon.ico"

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "README.md", "CNAME", "Gemfile", "Gemfile.md", "vendor"]

gems:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-paginate

whitelist:
  - jekyll-redirect-from

sass:
    sass_dir: _sass
