# Site settings
title: Francho(lab)... forjando ideicas
email: pub@francho.org
description: >
  Francho Joven Araus (aka @francholab). Unutopico, maño, geek, artesano de software, aprendiz ágil, programador en activo, sysop retirado, emocionado con Zagales Hacklab, papá a tiempo completo...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://francho.org" # the base hostname & protocol for your site
twitter_username: francholab
github_username:  francho
permalink: /:year/:month/:day/:title

# Build settings
markdown: kramdown
